# Generated by Django 5.2.4 on 2026-07-16 15:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp."
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "first_name",
                    models.CharField(help_text="Lead first name.", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Lead last name.", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Lead email address.", max_length=254, unique=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Lead phone number.", max_length=30
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        help_text="Company associated with the lead.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                        ],
                        db_index=True,
                        default="new",
                        help_text="Current lead lifecycle status.",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the lead."
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
