# Generated by Django 5.2.4 on 2026-07-16 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp."
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full name of the lead.", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Lead email address.", max_length=254, unique=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Lead phone number.", max_length=30
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("referral", "Referral"),
                            ("social", "Social Media"),
                            ("event", "Event"),
                        ],
                        db_index=True,
                        help_text="Lead acquisition source.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("assigned", "Assigned"),
                            ("contacted", "Contacted"),
                            ("converted", "Converted"),
                            ("closed_lost", "Closed Lost"),
                        ],
                        db_index=True,
                        default="new",
                        help_text="Current lead lifecycle status.",
                        max_length=20,
                    ),
                ),
                (
                    "sla_deadline",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Deadline for first contact.",
                        null=True,
                    ),
                ),
                (
                    "first_contacted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time when lead was first successfully contacted.",
                        null=True,
                    ),
                ),
                (
                    "converted_at",
                    models.DateTimeField(
                        blank=True, help_text="Time when lead was converted.", null=True
                    ),
                ),
                (
                    "assigned_advisor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Advisor responsible for this lead.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
